---
- title: "Letters: a, e, n, t"
  base_speed:
    wpm: 5
    farnsworth: 5
  incr_speed:
    wpm: 8
    farnsworth: 5
  words:
    - A
    - N
    - an
    - anna
    - T
    - at
    - tan
    - ant
    - E
    - ten
    - eat
    - net
    - neat
    - tent

- title: "Letters: m, i"
  base_speed:
    wpm: 8
    farnsworth: 5
  incr_speed:
    wpm: 8
    farnsworth: 8
  words:
    - M
    - team
    - man
    - mean
    - meet
    - meant
    - I
    - nine
    - mine
    - mint
    - intimate
    - annie

