---
- title: "Letters: a, e, n, t"
  base_speed:
    wpm: 5
    farnsworth: 5
  incr_speed:
    wpm: 8
    farnsworth: 5
  words:
    - a
    - n
    - an
    - anna
    - t
    - at
    - tan
    - ant
    - e
    - ten
    - eat
    - net
    - neat
    - tent

- title: "Letters: m, i"
  base_speed:
    wpm: 5
    farnsworth: 5
  incr_speed:
    wpm: 8
    farnsworth: 5
  words:
    - m
    - team
    - man
    - mean
    - meet
    - meant
    - i
    - nine
    - mine
    - mint
    - intimate
    - annie

- title: "Letters: o, s"
  base_speed:
    wpm: 8
    farnsworth: 5
  incr_speed:
    wpm: 8
    farnsworth: 8
  words:
    - o
    - too
    - note
    - moon
    - notion
    - tomato
    - s
    - sit
    - some
    - east
    - mission
    - estimate

- title: "Review: first eight letters"
  base_speed:
    wpm: 8
    farnsworth: 5
  incr_speed:
    wpm: 8
    farnsworth: 8
  words:
    - moment
    - statement
    - animation
    - testament
    - tension
    - instant
    - oasis
    - season
    - estate
    - nominations

- title: "Review and speed practice: 8 - 10 WPM"
  base_speed:
    wpm: 8
    farnsworth: 8
  incr_speed:
    wpm: 10
    farnsworth: 8
  words:
    - moment
    - statement
    - animation
    - testament
    - tension
    - instant
    - oasis
    - season
    - estate
    - nominations

- title: "Letters: h, r"
  base_speed:
    wpm: 8
    farnsworth: 8
  incr_speed:
    wpm: 10
    farnsworth: 8
  words:
    - h
    - the
    - heat
    - theme
    - host
    - shame
    - r
    - rate
    - store
    - enter
    - interest
    - harris

- title: "Letters: d, l"
  base_speed:
    wpm: 8
    farnsworth: 8
  incr_speed:
    wpm: 10
    farnsworth: 8
  words:
    - d
    - date
    - and
    - media
    - domain
    - amendment
    - l
    - lime
    - roll
    - lesson
    - malta
    - threshold

- title: "Review: first 12 letters"
  base_speed:
    wpm: 8
    farnsworth: 8
  incr_speed:
    wpm: 10
    farnsworth: 8
  words:
    - homeland
    - lender
    - denial
    - remedies
    - endorsement
    - transmit
    - isolation
    - oriental
    - determine
    - metadata

- title: "Review and speed practice: 8 - 10 WPM"
  base_speed:
    wpm: 10
    farnsworth: 8
  incr_speed:
    wpm: 10
    farnsworth: 10
  words:
    - homeland
    - lender
    - denial
    - remedies
    - endorsement
    - transmit
    - isolation
    - oriental
    - determine
    - metadata

- title: "Review and speed practice: 10 - 12 WPM"
  base_speed:
    wpm: 10
    farnsworth: 10
  incr_speed:
    wpm: 12
    farnsworth: 10
  words:
    - homeland
    - lender
    - denial
    - remedies
    - endorsement
    - transmit
    - isolation
    - oriental
    - determine
    - metadata

- title: "Letters: c, u"
  base_speed:
    wpm: 10
    farnsworth: 10
  incr_speed:
    wpm: 12
    farnsworth: 10
  words:
    - c
    - colonial
    - scientist
    - essence
    - control
    - recommend
    - u
    - sauce
    - manual
    - cloud
    - conclude
    - construction

- title: "Letters: w, f"
  base_speed:
    wpm: 10
    farnsworth: 10
  incr_speed:
    wpm: 12
    farnsworth: 10
  words:
    - w
    - show
    - writer
    - tower
    - sweden
    - warrant
    - f
    - fill
    - fiscal
    - after
    - fraud
    - referral

- title: "Review: first 16 letters"
  base_speed:
    wpm: 10
    farnsworth: 10
  incr_speed:
    wpm: 12
    farnsworth: 10
  words:
    - renew
    - thunder
    - chelsea
    - considers
    - enhancements
    - newfoundland
    - momentum
    - commitments
    - fundamentals
    - dictionaries

- title: "Review and speed practice: 10 - 12 WPM"
  base_speed:
    wpm: 12
    farnsworth: 10
  incr_speed:
    wpm: 12
    farnsworth: 12
  words:
    - renew
    - thunder
    - chelsea
    - considers
    - enhancements
    - newfoundland
    - momentum
    - commitments
    - fundamentals
    - dictionaries

- title: "Review and speed practice: 12 - 15 WPM"
  base_speed:
    wpm: 12
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 12
  words:
    - renew
    - thunder
    - chelsea
    - considers
    - enhancements
    - newfoundland
    - momentum
    - commitments
    - fundamentals
    - dictionaries

- title: "Letters: g, y"
  base_speed:
    wpm: 12
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 12
  words:
    - g
    - gate
    - organ
    - guided
    - integral
    - assuming
    - y
    - cycle
    - candy
    - suddenly
    - grocery
    - alloy

- title: "Letters: p, b"
  base_speed:
    wpm: 12
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 12
  words:
    - p
    - part
    - rope
    - prime
    - duplicate
    - propose
    - b
    - robe
    - barrier
    - mobile
    - chamber
    - arbitrary

- title: "Review: first 20 letters"
  base_speed:
    wpm: 12
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 12
  words:
    - touring
    - rebound
    - presently
    - pursuit
    - barbie
    - asylum
    - bacterial
    - fridge
    - highway
    - annoying

- title: "Review and speed practice: 15 WPM"
  base_speed:
    wpm: 15
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 15
  words:
    - touring
    - rebound
    - presently
    - pursuit
    - barbie
    - asylum
    - bacterial
    - fridge
    - highway
    - annoying

- title: "Letters: v, k"
  base_speed:
    wpm: 15
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 15
  words:
    - v
    - five
    - seven
    - heavily
    - observe
    - vaccine
    - k
    - know
    - folks
    - think
    - yukon
    - tackle

- title: "Letter: j"
  base_speed:
    wpm: 15
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 15
  words:
    - j
    - job
    - july
    - joy
    - juice
    - adjust
    - joke
    - object
    - junction
    - jacksonville

- title: "Letter: x"
  base_speed:
    wpm: 15
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 15
  words:
    - x
    - text
    - index
    - syntax
    - exhibit
    - fixes
    - examine
    - exclude
    - texture
    - relaxation

- title: "Letter: q"
  base_speed:
    wpm: 15
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 15
  words:
    - q
    - quite
    - question
    - request
    - require
    - quality
    - quarters
    - aquatic
    - consequence
    - frequency

- title: "Letter: z"
  base_speed:
    wpm: 15
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 15
  words:
    - z
    - size
    - pizza
    - puzzle
    - zone
    - buzz
    - realize
    - bronze
    - characterize
    - personalized

- title: "Review: ALL the letters!"
  base_speed:
    wpm: 15
    farnsworth: 12
  incr_speed:
    wpm: 15
    farnsworth: 15
  words:
    - whistle
    - apathetic
    - useless
    - advertisement
    - detail
    - weak
    - texture
    - fowl
    - faded
    - raise
    - mailbox
    - high
    - polite
    - one
    - jar
    - invite
    - distinct
    - collect
    - half
    - growth
    - heat
    - bare
    - zephyr
    - smile
    - two
    - delirious
    - committee
    - shock
    - quickest
    - petite
    - rule
    - stitch
    - rapid
    - calculate
    - talented
    - plane
    - drab
    - laborer
    - wave
    - sudden
    - stomach
    - current
    - drum
    - market
    - panoramic
    - good
    - succeed
    - wealthy
    - grumpy
    - hope
    - aloof
    - adventurous
    - impolite
    - frame
    - learned
    - comparison
    - underwear
    - employ
    - cut
    - price
    - park
    - sheep
    - pretend
    - aspiring
    - sheet
    - brake

- title: "Speed practice: 15 - 18 WPM"
  base_speed:
    wpm: 15
    farnsworth: 15
  incr_speed:
    wpm: 18
    farnsworth: 15
  words:
    - whistle
    - apathetic
    - useless
    - advertisement
    - detail
    - weak
    - texture
    - fowl
    - faded
    - raise
    - mailbox
    - high
    - polite
    - one
    - jar
    - invite
    - distinct
    - collect
    - half
    - growth
    - heat
    - bare
    - zephyr
    - smile
    - two
    - delirious
    - committee
    - shock
    - quickest
    - petite
    - rule
    - stitch
    - rapid
    - calculate
    - talented
    - plane
    - drab
    - laborer
    - wave
    - sudden
    - stomach
    - current
    - drum
    - market
    - panoramic
    - good
    - succeed
    - wealthy
    - grumpy
    - hope
    - aloof
    - adventurous
    - impolite
    - frame
    - learned
    - comparison
    - underwear
    - employ
    - cut
    - price
    - park
    - sheep
    - pretend
    - aspiring
    - sheet
    - brake

- title: "Speed practice: 18 WPM"
  base_speed:
    wpm: 18
    farnsworth: 15
  incr_speed:
    wpm: 18
    farnsworth: 18
  words:
    - whistle
    - apathetic
    - useless
    - advertisement
    - detail
    - weak
    - texture
    - fowl
    - faded
    - raise
    - mailbox
    - high
    - polite
    - one
    - jar
    - invite
    - distinct
    - collect
    - half
    - growth
    - heat
    - bare
    - zephyr
    - smile
    - two
    - delirious
    - committee
    - shock
    - quickest
    - petite
    - rule
    - stitch
    - rapid
    - calculate
    - talented
    - plane
    - drab
    - laborer
    - wave
    - sudden
    - stomach
    - current
    - drum
    - market
    - panoramic
    - good
    - succeed
    - wealthy
    - grumpy
    - hope
    - aloof
    - adventurous
    - impolite
    - frame
    - learned
    - comparison
    - underwear
    - employ
    - cut
    - price
    - park
    - sheep
    - pretend
    - aspiring
    - sheet
    - brake

- title: "Speed practice: 18 WPM"
  base_speed:
    wpm: 18
    farnsworth: 18
  incr_speed:
    wpm: 20
    farnsworth: 18
  words:
    - fixed
    - aback
    - relax
    - wholesale
    - unhealthy
    - redundant
    - yard
    - telling
    - thin
    - sound
    - shoe
    - cap
    - bleach
    - wild
    - push
    - snails
    - cemetery
    - fortunate
    - downtown
    - unbecoming
    - victorious
    - female
    - girl
    - cushion
    - fit
    - shirt
    - tie
    - insect
    - treatment
    - ship
    - rod
    - empty
    - obsolete
    - wiry
    - complex
    - insurance
    - jealous
    - memorize
    - radiate
    - nest
    - sneaky
    - squash
    - umbrella
    - fretful
    - fancy
    - start
    - suit
    - excited
    - label
    - leg
    - daffy
    - boiling
    - capricious
    - impartial
    - tightfisted
    - education
    - painful
    - elbow
    - milk
    - motionless

- title: "Speed practice: 20 WPM"
  base_speed:
    wpm: 20
    farnsworth: 18
  incr_speed:
    wpm: 20
    farnsworth: 20
  words:
    - fixed
    - aback
    - relax
    - wholesale
    - unhealthy
    - redundant
    - yard
    - telling
    - thin
    - sound
    - shoe
    - cap
    - bleach
    - wild
    - push
    - snails
    - cemetery
    - fortunate
    - downtown
    - unbecoming
    - victorious
    - female
    - girl
    - cushion
    - fit
    - shirt
    - tie
    - insect
    - treatment
    - ship
    - rod
    - empty
    - obsolete
    - wiry
    - complex
    - insurance
    - jealous
    - memorize
    - radiate
    - nest
    - sneaky
    - squash
    - umbrella
    - fretful
    - fancy
    - start
    - suit
    - excited
    - label
    - leg
    - daffy
    - boiling
    - capricious
    - impartial
    - tightfisted
    - education
    - painful
    - elbow
    - milk
    - motionless

- title: "Speed practice: 20 WPM, no spoken words"
  suppress_spoken: true
  base_speed:
    wpm: 20
    farnsworth: 18
  incr_speed:
    wpm: 20
    farnsworth: 20
  words:
    - fixed
    - aback
    - relax
    - wholesale
    - unhealthy
    - redundant
    - yard
    - telling
    - thin
    - sound
    - shoe
    - cap
    - bleach
    - wild
    - push
    - snails
    - cemetery
    - fortunate
    - downtown
    - unbecoming
    - victorious
    - female
    - girl
    - cushion
    - fit
    - shirt
    - tie
    - insect
    - treatment
    - ship
    - rod
    - empty
    - obsolete
    - wiry
    - complex
    - insurance
    - jealous
    - memorize
    - radiate
    - nest
    - sneaky
    - squash
    - umbrella
    - fretful
    - fancy
    - start
    - suit
    - excited
    - label
    - leg
    - daffy
    - boiling
    - capricious
    - impartial
    - tightfisted
    - education
    - painful
    - elbow
    - milk
    - motionless

